// utils.js
const { ethers } = require("hardhat");
// const AddressZero = ethers.constants.AddressZero;

/**
 * Default values for a UserOperation object.
 */
// const DefaultsForUserOp = {
//   sender: AddressZero,
//   nonce: 0,
//   initCode: '0x',
//   callData: '0x',
//   callGasLimit: 0,
//   verificationGasLimit: 150000, // Default verification gas
//   preVerificationGas: 21000,   // Covers calldata cost
//   maxFeePerGas: 0,
//   maxPriorityFeePerGas: 1e9,
//   paymaster: AddressZero,
//   paymasterData: '0x',
//   paymasterVerificationGasLimit: 300000,
//   paymasterPostOpGasLimit: 0,
//   signature: '0x',
// };

/**
 * Converts the proof JSON into an array of hexadecimal strings for Plonk verification.
 * @param {Object} proofJson - The proof object generated by snarkjs.plonk.fullProve.
 * @returns {Array} - An array of hexadecimal strings representing the proof.
 */
function parseProof(proofJson) {
    const proof = [
        "0x" + BigInt(proofJson.A[0]).toString(16), 
        "0x" + BigInt(proofJson.A[1]).toString(16), 
        "0x" + BigInt(proofJson.B[0]).toString(16), 
        "0x" + BigInt(proofJson.B[1]).toString(16), 
        "0x" + BigInt(proofJson.C[0]).toString(16), 
        "0x" + BigInt(proofJson.C[1]).toString(16), 
        "0x" + BigInt(proofJson.Z[0]).toString(16), 
        "0x" + BigInt(proofJson.Z[1]).toString(16), 
        "0x" + BigInt(proofJson.T1[0]).toString(16), 
        "0x" + BigInt(proofJson.T1[1]).toString(16), 
        "0x" + BigInt(proofJson.T2[0]).toString(16), 
        "0x" + BigInt(proofJson.T2[1]).toString(16), 
        "0x" + BigInt(proofJson.T3[0]).toString(16), 
        "0x" + BigInt(proofJson.T3[1]).toString(16), 
        "0x" + BigInt(proofJson.Wxi[0]).toString(16), 
        "0x" + BigInt(proofJson.Wxi[1]).toString(16), 
        "0x" + BigInt(proofJson.Wxiw[0]).toString(16), 
        "0x" + BigInt(proofJson.Wxiw[1]).toString(16), 
        "0x" + BigInt(proofJson.eval_a).toString(16), 
        "0x" + BigInt(proofJson.eval_b).toString(16), 
        "0x" + BigInt(proofJson.eval_c).toString(16), 
        "0x" + BigInt(proofJson.eval_s1).toString(16), 
        "0x" + BigInt(proofJson.eval_s2).toString(16), 
        "0x" + BigInt(proofJson.eval_zw).toString(16), 
   ];

    return proof;
}

/**
 * Fills missing fields in a UserOperation object with default values.
 * @param {Object} op - A partial UserOperation object.
 * @param {Object} defaults - Default values for the UserOperation.
 * @returns {Object} - A complete UserOperation object with defaults applied.
 */
function fillUserOpDefaults(op, defaults) {
    const partial = { ...op };
    // Remove keys with null or undefined values
    for (const key in partial) {
      if (partial[key] == null) {
        delete partial[key];
      }
    }
    // Merge defaults with provided partial UserOperation
    const filled = { ...defaults, ...partial };
    return filled;
  }
  
  module.exports = {
    fillUserOpDefaults,
  };

// Export the function for use in other modules
module.exports = {
    parseProof,
    fillUserOpDefaults
};